### ISSUE TITLE
README and docs refer to `next-test-endpoint`

### ISSUE THREAD

**Issue by kmjennison** [Xunnamius/next-test-api-route-handler#1]
The examples should refer to `next-test-api-route-handler` instead of `next-test-endpoint`. Small PR incoming with the fixes.

I also wanted to say thanks for building this 😃  I'd been moving toward building something similar after getting tired of mocking `req`/`res`. Linked to this module from a few related Next.js discussions:
https://github.com/vercel/next.js/discussions/15166
https://github.com/vercel/next.js/discussions/17528

**Comment by Xunnamius** [comment]
Nice catch, thanks. And yeah, after copying and pasting this snippet for the nth time, it was about time to package it :smile:
