### ISSUE TITLE
originalGlobalFetch is not a function

### ISSUE THREAD

**Issue by danactive** [Xunnamius/next-test-api-route-handler#1039]
<details open><summary><strong>The problem</strong></summary>

I tried NTARH v4.0.5 with Next.js v14.1.4 or v14.2.1 and my unit tests fail with this reason:
`originalGlobalFetch is not a function`

Sample unit test that fails

```javascript
import { testApiHandler } from 'next-test-api-route-handler'

test('Sample test that fails on line 8', async () => {
  await testApiHandler({
    params: { id: 5 },
    pagesHandler: (req, res) => res.status(200).send({ id: req.query.id }),
    test: async ({ fetch }) =>
      expect((await fetch({ method: 'POST' })).json()).resolves.toStrictEqual({
        id: 5
      })
  });
})

```

</details>

<details><summary><strong>Reproduction steps</strong></summary>

1. Clone the history repo I made: https://github.com/danactive/history/tree/update-deps
2. `nvm use` Match node.js version
3. `npm ci` Install deps
4. `npm test` Run test suite
5. See error "originalGlobalFetch is not a function" at test "Gallery endpoint › Expect result › * GET has gallery", which shouldn't be happening
</details>

<details><summary><strong>Expected behavior</strong></summary>

1. Clone the history repo I made: https://github.com/danactive/history/tree/update-deps
2. `nvm use` Match node.js version
3. `npm ci` Install deps
4. `npm test` Run test suite
5. All tests should pass

</details>

<details><summary><strong>Additional context</strong></summary>

- OS: macos Sonoma 14.3
- Node version: 20
- Babel: No
- TypeScript: yes, version 5.2.2
- Browser: N/A using Node.js CLI
- [List of installed packages](https://github.com/danactive/history/blob/update-deps/package.json)

</details>

**Comment by Xunnamius** [comment]
Hmm. Could you be using an old version of Node.js? Either way, I'll take a look.

**Comment by Xunnamius** [comment]
Alright, I took a look at your repo (thanks for sharing a reproducible example!) and was able to recreate your issue. This is not an NTARH issue. Rather, this is a [known issue](https://github.com/jestjs/jest/issues/13834#issuecomment-1407375787) with the [jsdom Jest testing environment](https://github.com/jsdom/jsdom/issues/1724). Your options are to [manually polyfill](https://stackoverflow.com/a/75399601/1367414) or [use the node testing environment](https://stackoverflow.com/a/76679669/1367414).
