### ISSUE TITLE
Allow this to be used with Vitest

### ISSUE THREAD

**Issue by EricImpact** [Xunnamius/next-test-api-route-handler#1060]
I would love to be able to use this package with our existing Vitest setup. Vitest generally plays very nicely with tests written for Jest, but no luck with this package I'm afraid. 

As an alternative, we're currently writing integration tests using Jest to complement our unit tests written for Vitest.

**Comment by Xunnamius** [comment]
Interesting. What errors are you getting with vitest?

**Comment by EricImpact** [comment]
Turns out this was user error. 🤦  Got it working now, so will close this issue.
