### ISSUE TITLE
IPv4 vs IPv6 failing tests in Jenkins CI pipeline

### ISSUE THREAD

**Issue by rosswilson2306** [Xunnamius/next-test-api-route-handler#1068]
<details open><summary><strong>The problem</strong></summary>

Credit to @bobf for the investigation and proposed solution for this.

I'm trying to run a test suite in a Jenkins CI pipeline. All tests run successfully in a local terminal but the route handler tests using  NTARH fail with the following error:
```
TypeError: fetch failed

    > 72 |         const response = await fetch({
         |                          ^
      73 |           method: 'GET',

      at test (app/api/sitemap.xml/sitemap-index.test.ts:72:26)
      at testApiHandler (node_modules/next-test-api-route-handler/dist/src/index.js:125:5)
      at Object.<anonymous> (app/api/sitemap.xml/sitemap-index.test.ts:57:5)

    Cause:
    connect ECONNREFUSED 127.0.0.1:37709
```
It was found that the issue lay [here](https://github.com/Xunnamius/next-test-api-route-handler/blob/main/src/index.ts#L305). Logging the value of `addr` on line 307 returns:
```
{ address: '::1', family: 'IPv6', port: 57977 }
```
but `localhost` in `localUrl` on line 321 resolves to  `127.0.0.1`, IPv4. 

</details>

<details><summary><strong>Reproduction steps</strong></summary>

We unfortunately can't provide access to the project repository as it is a private repo. But I would imagine running a similar route handler test using NTARH would throw the same error.

</details>

<details><summary><strong>Expected behavior</strong></summary>

Tests that run successfully in the terminal should run in Jenkins CI pipeline successfully.

</details>

<details><summary><strong>Suggested solution</strong></summary>

The following change allowed tests to pass as expected in Jenkins.

```tsx
const { address, port } = await new Promise((resolve, reject) => {
      server?.listen(0, 'localhost', undefined, () => {
        const addr = server?.address();
        if (!addr || typeof addr === 'string') {
          reject(new Error('assertion failed unexpectedly: server did not return AddressInfo instance'));
        } else {
          resolve({ port: addr.port, address: addr.family === 'IPv6' ? `[${addr.address}]` : addr.address });
        }
      });
    });
    const localUrl = `http://${address}:${port}`;
```

</details>

<details><summary><strong>Additional context</strong></summary>

- NextJS 14.2.5
- Node version: 22.6.0
- next-test-api-route-handler: 4.0.8
- TypeScript: 5.5.4

</details>

**Comment by Xunnamius** [comment]
Thanks for this! I'll try to merge this in this week.

**Comment by Xunnamius** [comment]
I haven't come up with a way to do a meaningful integration test of this patch, but the units all pass and things should be working now. If not, ping me and I'll reopen this issue.

**Comment by rosswilson2306** [comment]
Thanks @Xunnamius

**Comment by rosswilson2306** [comment]
@Xunnamius I've updated the version and our tests are all now passing in Jenkins, thanks again.
