### ISSUE TITLE
Potential incompatibility with next@4.2.12

### ISSUE THREAD

**Issue by Xunnamius** [Xunnamius/next-test-api-route-handler#1076]
<details open><summary><strong>The problem</strong></summary>

Looks like the internals have shifted with this version of Next. Investigating.

Semi-related: looks like there might be a bug in https://github.com/vercel/next.js/blame/ac4a1c6730672bf2783414e51f64b49519ddffdb/packages/next/src/server/route-modules/app-route/module.ts#L520-L521 (is one of those `POST`s supposed to be a `PUT`?)

UPDATE: narrowed down the issue to `isStaticGeneration` being set to `true` in the `AsyncLocalStorage` instance context triggering the problematic static generation logic. Looks like some API routes are gonna get statically generated now.

Fix incoming.

</details>

<details><summary><strong>Reproduction steps</strong></summary>

See failing actions.

</details>

**Comment by lordphnx** [comment]
We are experiencing the following, is it related?

```
Cannot read properties of undefined (reading 'multiZoneDraftMode')
        at multiZoneDraftMode ([redacted]/node_modules/next/src/server/api-utils/node/api-resolver.ts:350:60)
        at IncomingMessage.getter [as previewData] ([redacted]/node_modules/next/src/server/api-utils/index.ts:209:21)
```

**Comment by Xunnamius** [comment]
@lordphnx Indeed it is. And thank you for #1077 on the Pages router side! I'll get that merged in after I've had a coffee. I'm investigating the app router side now, hopefully the fix is as straightforward.

**Comment by lordphnx** [comment]
@Xunnamius are there any steps you need from me to get this into a version we can use?

The "bug" is currently inhibiting our CI pipelines, so we would be very happy to use this small fix.

**Comment by Xunnamius** [comment]
I was going to push both Pages and App router fixes in the same release, but I can cut a patch release with just this fix 👍🏿

**Comment by lordphnx** [comment]
Would greatly appreciate that ❤️

**Comment by Xunnamius** [comment]
[`ntarh@4.0.10` is live](https://www.npmjs.com/package/next-test-api-route-handler/v/4.0.10)
