### ISSUE TITLE
stack trace from error on `test` function?

### ISSUE THREAD

**Issue by hems** [Xunnamius/next-test-api-route-handler#197]
I been testing a route that was failing due to a problem with `axios` and i was getting a `SyntaxError` from inside of axios but i couldn't figure out  where the error was coming from because it seems next-test-api-router-handler was throwing only a string and not the entire error / stack trace?

![image](https://user-images.githubusercontent.com/27327/117906589-1d077580-b2cd-11eb-8bbd-4bca66f40b0c.png)

### The solution

throw the entire error with stack trace when an error happen? Would that possible or is that a limitation from `apiResolver`?

That would help a lot when debugging errors on tests!

Thanks for your help / library

**Comment by Xunnamius** [comment]
Hmm. Right now [NTARH](https://github.com/Xunnamius/next-test-api-route-handler/blob/75832099f4c4d0e329aca469ac16c8a25100c26d/src/index.ts#L78) uses [`try { ... } finally { ... }`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#the_finally-block) where AFAIK the error will pass through. Unless Babel compilation is mangling error handling, it might be an issue of Jest reporter configuration :)

**Comment by hems** [comment]
turns out it was a problem with `axios` and not with this library, thanks for looking at it tough!
