### ISSUE TITLE
Add response.cookies field for easier access to multiple cookies

### ISSUE THREAD

**Issue by steve-taylor** [Xunnamius/next-test-api-route-handler#373]
<details open><summary><strong>The problem</strong></summary>

When testing a Next.js API route that sets multiple cookies, only the most recent `Set-Cookie` header is detected.

</details>

<details><summary><strong>Reproduction steps</strong></summary>

Clone [this repo](https://github.com/steve-taylor/next-test-api-route-handler-reproduction) and run the test (instructions in README.md).

The test is expected to fail due to this bug. (However, I don't know what a pass looks like, as multiple cookies are encoded in a different way than other headers.)

</details>

<details><summary><strong>Suggested solution</strong></summary>

As this is partially caused by a deficiency in the fetch API, consider adding a `cookies` field to the response, so we can do something like this:

```js
import {serialize} from 'cookie'
import {testApiHandler} from 'next-test-api-route-handler'

describe('next-test-api-route-handler bug', () => {
    it('is a bug', async () => {
        await testApiHandler({
            handler: async (_req, res) => {
                res.setHeader('Set-Cookie', serialize('access_token', '1234'))
                res.setHeader('Set-Cookie', serialize('refresh_token', '5678'))
                res.status(204).end()
            },
            test: async ({fetch}) => {
                const response = await fetch({
                    method: 'POST',
                    headers: {'Content-Type': 'application/json'},
                    body: JSON.stringify({})
                })

                // Test hypothetical cookies property
                expect(response.cookies.sort()).toEqual([
                    'access_token=1234',
                    'refresh_token=5678',
                ])
            },
        })
    })
})
```

</details>

**Comment by Xunnamius** [comment]
First, thank you for making a reproducible example! Most people don't, which makes things more difficult.

As for handling multiple `set-cookie` headers, a couple things:

1. [Node handles consecutive calls to `setHeader()` as overwriting the result of the previous call](https://nodejs.org/dist/latest-v17.x/docs/api/http.html#http_response_setheader_name_value). Specifically:

> If this header already exists in the to-be-sent headers, its value will be replaced. Use an array of strings here to send multiple headers with the same name.

2. `node-fetch` (which `unfetch` exposes) comes with the [`res.headers.raw()` method for accessing raw response headers](https://github.com/node-fetch/node-fetch#extract-set-cookie-header). This was added specifically to facilitate `set-cookie` header extraction.

I updated the `bug.test.js` file in your MRE with the following:

```javascript
import { serialize, parse } from 'cookie';
import { testApiHandler } from 'next-test-api-route-handler';

describe('next-test-api-route-handler bug', () => {
  it('is NOT a bug ;)', async () => {
    await testApiHandler({
      handler: async (_req, res) => {
        // res.setHeader('Set-Cookie', serialize('access_token', '1234'))
        // res.setHeader('Set-Cookie', serialize('refresh_token', '5678'))
        // ! WARNING: consecutive calls to setHeader('X') overwrite previous!
        res.setHeader('Set-Cookie', [
          serialize('access_token', '1234', { expires: new Date() }),
          serialize('refresh_token', '5678')
        ]);
        res.status(204).send();
      },
      test: async ({ fetch }) => {
        const response = await fetch({
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({})
        });

        const cookies = response.headers.raw()['set-cookie'].map(parse);

        expect(cookies).toStrictEqual([
          expect.objectContaining({
            access_token: '1234',
            Expires: expect.any(String)
          }),
          expect.objectContaining({ refresh_token: '5678' })
        ]);
      }
    });
  });
});
```
The test passes. Does this address your issue?

**Comment by steve-taylor** [comment]
> ```js
>         res.setHeader('Set-Cookie', [
>           serialize('access_token', '1234', { expires: new Date() }),
>           serialize('refresh_token', '5678')
>         ]);
> ```

This is definitely the way to set multiple cookies in Next.js, so thank you! I tested it in a real Next.js API route and it works perfectly.

> As for adding a `cookies` field to the response object NTARH returns—which would be defined with something like `response.cookies = response.headers.raw()['set-cookie'].map(parse)`—I think that's a worthy enhancement. Is this the API you had in mind?

Yes, for two reasons. 1. The `Headers` class can't accommodate multiple `Set-Cookie` headers, and 2. The real `fetch` doesn't include `Set-Cookie` headers, which is inconsistent with current NTARH behavior.

As for my test, with your changes to `res.setHeader`, I changed the assertion from a negative to a positive one and now it looks like this (and passes):

```js
import {serialize} from 'cookie'
import {testApiHandler} from 'next-test-api-route-handler'

describe('next-test-api-route-handler bug', () => {
    it('is a bug', async () => {
        await testApiHandler({
            handler: async (_req, res) => {
                res.setHeader('Set-Cookie', [
                    serialize('access_token', '1234'),
                    serialize('refresh_token', '5678')
                ])
                res.status(204).end()
            },
            test: async ({fetch}) => {
                const response = await fetch({
                    method: 'POST',
                    headers: {'Content-Type': 'application/json'},
                    body: JSON.stringify({})
                })

                expect(response.headers.get('Set-Cookie')).toEqual(
                    'access_token=1234, refresh_token=5678'
                )
            },
        })
    })
})
```

This isn't the way multiple cookie headers work, but for now it's a viable way forward. I had been working around this issue by mocking and spying on my cookie setting function, but this is better. I personally consider this a workaround given the issues identified above and would like to see, if possible, the introduction of the proposed `cookies` property, with `Set-Cookie` excluded from `headers`. It would definitely be a breaking change.

> First, thank you for making a reproducible example! Most people don't, which makes things more difficult.

It's the least I could do. NTARH has saved me a bunch of time.
