### ISSUE TITLE
Support for edge function API

### ISSUE THREAD

**Issue by rhys-e** [Xunnamius/next-test-api-route-handler#773]
It'd be great if we could get an update to the `handler` parameter to also support the edge function format 

i.e. `handler(req: NextRequest): Promise<Response>` (rather than the `NextApiRequest/NextApiResponse`)

Thanks

**Comment by Xunnamius** [comment]
Hmm. I've been thinking about this for a little while now. It will depend on how Next.js internals handle edge functions. I'll look into it for the next major NTARH release.

**Comment by Xunnamius** [comment]
Addressed by https://github.com/Xunnamius/next-test-api-route-handler/commit/e2d8865b3b91f735e98d6c0a0c1e1c88d41e8802
