### ISSUE TITLE
Expose function callbacks to TestApiClient instance in next major version

### ISSUE THREAD

**Issue by zero734kr** [Xunnamius/next-test-api-route-handler#85]
### The solution

I think these ``test``, ``requestPatcher`` and ``responsePatcher`` functions are unnecessary to be defined when creating tester instance. It's so limited when we need to create tester with some options dynamically and asynchronous work with Promises is better than callbacks. So, to avoid dirty codes caused by callbacks, it can be solved by exposing these functions like setting headers to be setted after the ``testApiHandler`` instance is created.

Example:

```js
const api = require("../../pages/api/someApiEndpoint")
const { TestApiClient } = require("next-test-api-route-handler")

// as class instance:
const tester = new TestApiClient({ handler: api })
// as function:
const tester = TestApiClient({ handler: api })

// Proposal 1: defining directly
tester.request.headers = { key: process.env.SPECIAL_TOKEN }
// Proposal 2: exposing 'setXXX' functions 
tester.request.setHeader('key', process.env.SPECIAL_TOKEN)

const example = await tester.fetch({ method: 'GET' }).then(r => r.json())

// test with test environments like jest
expect(example).toBe('test')

// Block tentative after test was already executed
tester.request.setHeader('test', 'error')
// Error: cannot set header after test was already executed
```

### Alternatives considered

I'm open to other suggestions, but if you dont want to expose everything because there are too many codes to be edited, you can only expose the ``test`` function and this will help me a lot.

<details><summary><strong>Additional context</strong></summary>

</details>

**Comment by Xunnamius** [comment]
Interesting. What use case does this alternative interface solve more elegantly that the current Promise-based interface does not? Keep in mind the `testApiHandler` function is meant to be self-contained. Specifically, it:

1. Spins up a mini-HTTP server listening on a unique port
2. Uses it to run your handler function in a Next-like context (where Next internals create special Request and Response instances)
3.  *Guarantees* that small HTTP server spins down cleanly before the test ends regardless of what your handler does

Seems like you want an interface that splits these steps up, and then adds some checks on the Request and Response objects Next creates, like with `setHeader`? I'm certainly open to a PR demonstrating this :)

If you're just looking for just "the `test` function," if you mean Next's API resolver, you can see it [here](https://github.com/Xunnamius/next-test-api-route-handler/blob/main/src/index.ts#L5).

**Comment by zero734kr** [comment]
I had not considered the structure and mechanism of the project was to apply features of my issue. Didn’t considered that was creating http server and I was in a hurry to submit feedback 😅.
