### ISSUE TITLE
Error: Invariant: Method expects to have requestAsyncStorage, none available

### ISSUE THREAD

**Issue by imprakharshukla** [Xunnamius/next-test-api-route-handler#875]
<details open><summary><strong> Error: Invariant: Method expects to have requestAsyncStorage, none available</strong></summary>

Hey! I am trying to test my app route handlers which are protected using Clerk.dev authentication.
When testing an endpoint which is not protected with clerk the test runs fine but as soon as an endpoint protected with clerk is tested it throws the following error:

```
 Error: Clerk: auth() and currentUser() are only supported in App Router (/app directory).
@acme/admin:test:       If you're using /pages, try getAuth() instead.
@acme/admin:test:       Original error: Error: Invariant: Method expects to have requestAsyncStorage, none available
```

</details>

<details><summary><strong>Reproduction steps</strong></summary>

1. Create a basic next app and install clerk following the guide at https://clerk.com/docs <br/>
2. Now try to create a test that tests a protected route, e.g:

```
import type { PageConfig } from "next";
import { testApiHandler } from "next-test-api-route-handler";

import {
  GET as getReqAdmin,
  PUT as putReqAdmin,
} from "../../app/api/admin/route";
import { prisma } from "../../lib/prismaClient";
import { orderSeedData, userSeedData } from "../testUtils/seedData";

beforeEach(async () => {
  await prisma.users.create({
    data: userSeedData,
  });
  await prisma.orders.create({
    data: orderSeedData,
  });
});

afterEach(async () => {
  await prisma.users.deleteMany();
  await prisma.users.deleteMany();
});

// Respect the Next.js config object if it's exported
const getReqHandler: typeof getReqAdmin & { config?: PageConfig } = getReqAdmin;
const putReqHandler: typeof putReqAdmin & { config?: PageConfig } = putReqAdmin;

describe("admin api", () => {
  it("should return 401 unauthorized", async () => {
    await testApiHandler({
      handler: getReqHandler,
      test: async ({ fetch }) => {
        const res = await fetch({ method: "GET" });
        await expect(res.status).resolves.toStrictEqual(401);
      },
    });
  });
});

```

</details>

<details><summary><strong>Expected behavior</strong></summary>

The test should pass since the library states that it is compatible with the app router.

</details>

<details><summary><strong>Additional context</strong></summary>

  System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 159.31 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.20.2 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 9.8.1 - ~/temp_turbo_order/<re>/node_modules/.bin/npm
    pnpm: 8.5.1 - ~/Library/pnpm/pnpm
</details>

</details>

**Comment by Xunnamius** [comment]
Interesting. I haven't looked at the repro yet, but this seems like this has to do with differences between the app router and the pages router (I've seen `requestAsyncStorage` when reading through the Next.js source). The next version of NTARH tries to use the app router module directly for app routed api handlers, which might solve this, though I'm still testing if this approach is stable and sensible. I'll update this thread after I've taken a closer look.
