### ISSUE TITLE
Incompatibility with next@12.5.4

### ISSUE THREAD

**Issue by Xunnamius** [Xunnamius/next-test-api-route-handler#887]
<details open><summary><strong>The problem</strong></summary>

One of the latest [GHA compat tests](https://github.com/Xunnamius/next-test-api-route-handler/actions) failed, so it looks like NTARH is incompatible with next@12.5.4. It's already fixed in my local version, so published fix is incoming.

</details>

<details><summary><strong>Reproduction steps</strong></summary>

</details>

**Comment by Xunnamius** [comment]
Hey! This issue is numbered #887 while the previous incompatibility issue is numbered #487... they're exactly 400 issues/PRs apart! Dunno why I find that neat, but there it is.

**Comment by tolivturnstile** [comment]
Hey there, I'm on Next 13.5.4 and still seeing this same issue 

```
Error: next-test-api-route-handler (NTARH) failed to import api-utils.js

  This is usually caused by:

    1. Using npm@<7 and/or node@<15, which doesn't install peer deps automatically (review install instructions)
    2. NTARH and the version of Next.js you installed are actually incompatible (please submit a bug report)

  Failed import attempts:

    - Headers is not defined
    - Cannot find module '/Users/tony/workspace/turnstile/web/src/typescript/turnstile/node_modules/next/dist/server/api-utils/node.js'
    - Cannot find module '/Users/tony/workspace/turnstile/web/src/typescript/turnstile/node_modules/next/dist/server/api-utils.js'
    - Cannot find module '/Users/tony/workspace/turnstile/web/src/typescript/turnstile/node_modules/next/dist/next-server/server/api-utils.js'
    - Cannot find package 'next-server'
```

if I dig into my `node_modules` I can confirm that those listed files do not exist, nor `next-server`

Is it possible I'm missing something? Thanks for the awesome work with this library !

**Comment by Xunnamius** [comment]
Hey @tolivturnstile, the first error in the list is "`Headers` is not defined". From a quick peek at [the Node docs](https://nodejs.org/api/globals.html#class-headers), it seems like global `Headers` was unflagged in Node 18 (the oldest LTS). I've been building and testing NTARH against Node versions that aren't [EoL](https://endoflife.date/nodejs). Are you using a Node version <18?

I'm leaning on corejs for this upcoming NTARH release, so, if this is the issue, I could look into adding Node 17/16 as a build and test target.

**Comment by tolivturnstile** [comment]
> Hey @tolivturnstile, the first error in the list is "`Headers` is not defined". From a quick peek at [the Node docs](https://nodejs.org/api/globals.html#class-headers), it seems like global `Headers` was unflagged in Node 18 (the oldest LTS). I've been building and testing NTARH against Node versions that aren't [EoL](https://endoflife.date/nodejs). Are you using a Node version <18?
> 
> I'm leaning on corejs for this upcoming NTARH release, so, if this is the issue, I could look into adding Node 17/16 as a build and test target.

You are 100 percent correct, I completely neglected to see that I'm using Node 16 🙃 . Should be fine for me to just update and go from here. Thank you for the quick response and tolerating my misunderstanding
