### ISSUE TITLE
Bypassing MSW does not work with MSW 2.X

### ISSUE THREAD

**Issue by Jokinen** [Xunnamius/next-test-api-route-handler#916]
This is more of a FYI.

In version `3.1.0`, the `x-msw-bypass` header was introduced in order to have better out of the box support for MSW.

MSW released a new version two weeks ago. Version 2.0 no longer respects the `x-msw-bypass` header. It seems that this header was considered to be an implementation detail as it's not documented as a breaking change.

MSW 2.0 has a new utility called [bypass](https://github.com/mswjs/msw/blob/a037e3a3f4f4d4cc712d2b3867b3410e4bcfaad6/src/core/bypass.ts#L4). Based on the implementation, it seems that the new header that gets bypassed is:

```
'x-msw-intention': 'bypass'
```

I'm not suggesting similar support should be implemented for MSW 2.x as existed fro MSW 1.x. I just want to bring this change into your attention.

<details><summary><strong>Alternatives and workarounds</strong></summary>

As a workaround, the old header can be respected in userland:

```
  server.listen({
    onUnhandledRequest(request, print) {
      if (request.headers.get('x-msw-bypass') === 'true') {
        return;
      }

      print.warning();
    },
  })
);
```

Not sure if the new `bypass` utility can be used in some way that allows the implementation to not depend on implementation details.

</details>

**Comment by Xunnamius** [comment]
Thanks for this! I'll release an update shortly.
