### ISSUE TITLE
App Router Examples

### ISSUE THREAD

**Issue by jamespantalones** [Xunnamius/next-test-api-route-handler#938]
According to the docs `NTARH got app router and edge route support in version 4.`.

However, I have been unable to find any examples of tests using the app router. Additionally, it seems like the types require a `NextApiRequest`/`NextApiReponse`, 

Finally, if I simply ignore the types, I see `API route returned a Response object in the Node.js runtime, this is not supported. Please use runtime: "edge" as an error in the response.`

I am guessing this is all supported based on the docs, but don't see how. Any ideas?

**Comment by Xunnamius** [comment]
Hey there, thanks for the interest. Version 4 doesn't technically exist yet except in that section of the appendix (that I perhaps updated prematurely).

NTARH is up next on my list 👍🏾 I hope to finish it before the end of this month and close out all open issues
